from colors import *

LIST_LENGTH = 250

RECT_WIDTH = 3
RECT_HEIGHT = 1

TOP_OFFSET = 0

RECTANGLES_COLOR = WHITE
BACKGROUND_COLOR = BLACK
FINISHED_RECTANGLES_COLOR = GREEN

SCREEN_WIDTH = RECT_WIDTH * LIST_LENGTH
SCREEN_HEIGHT = (SCREEN_WIDTH // RECT_WIDTH)*RECT_HEIGHT + TOP_OFFSET