from colors import *

LIST_LENGTH = 512

RECT_WIDTH = 2
RECT_HEIGHT = 1.25

TOP_OFFSET = 0

RECT_COLOR = WHITE
BACKGROUND_COLOR = BLACK
FINISHED_RECTANGLES_COLOR = GREEN

SCREEN_WIDTH = RECT_WIDTH * LIST_LENGTH
SCREEN_HEIGHT = (SCREEN_WIDTH // RECT_WIDTH)*RECT_HEIGHT + TOP_OFFSET